In [1]:
# ~~ TERCEROS ~~ #
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# ~~ ESTE PROYECTO ~~ #
import set_paths
from config.paths import *
from src.preprocessing import concat_tables
from src.mkt import (embudo, 
                     add_unique_interested, 
                     join_inter_crm, 
                     traspasos_por_pasante
)
from src.utils import get_files
from src.kpis import evci_pipeline, irt_pipeline

# EMBUDOS
### Exposición -> Visualizaciones -> Consultas recibidas

## TOTAL MKT

In [3]:
embudo_mkt = evci_pipeline(estad_portales= ESTAD_PORTALES,
              inter_portales = INTERESADOS,
              pct_decimals = 3,
              start = 2,
              stop = 4)
embudo_mkt

                 conteo  pct_tot  pct_rel
Exposición       226173    1.000    1.000
Visualizaciones    8656    0.038    0.038
Interesados         203    0.001    0.023

## POR PORTAL

In [4]:
stats = [pd.read_excel(ESTAD_PORTALES / file) for file in get_files(ESTAD_PORTALES)]
inter = [pd.read_excel(INTERESADOS / file) for file in get_files(INTERESADOS)]
for i in range(4):
    embudo_portal = evci_pipeline(estad_portales= stats[i],
              inter_portales = inter[i],
              pct_decimals = 3,
              start = i,
              stop = i+1)
    print(f" ~~ PORTAL {i+1} ~~ ")
    print(embudo_portal)

 ~~ PORTAL 1 ~~
                 conteo  pct_tot  pct_rel
Exposición       146410    1.000    1.000
Visualizaciones    6546    0.045    0.045
Interesados         141    0.001    0.022
 ~~ PORTAL 2 ~~
                 conteo  pct_tot  pct_rel
Exposición       128418    1.000    1.000
Visualizaciones    4576    0.036    0.036
Interesados          83    0.001    0.018
 ~~ PORTAL 3 ~~
                 conteo  pct_tot  pct_rel
Exposición        36337    1.000    1.000
Visualizaciones    2270    0.062    0.062
Interesados          78    0.002    0.034
 ~~ PORTAL 4 ~~
                 conteo  pct_tot  pct_rel
Exposición        61418    1.000    1.000
Visualizaciones    1810    0.029    0.029
Interesados          42    0.001    0.023

## INTERESADOS vs REGISTROS vs TRASPASOS

### MARKETING

In [5]:
crm_df = pd.read_csv(CRM / get_files(CRM)[0])
irt_pipeline(crm_df= crm_df, 
             interesados=  INTERESADOS)

             conteo  pct_tot  pct_rel
Interesados     204    1.000    1.000
Registrados     199    0.975    0.975
Traspasados     199    0.975    1.000

## Por portal

In [6]:
for i in range(4):
    irt = irt_pipeline(crm_df= crm_df, 
             interesados= inter[i])
    print(f" ~~ PORTAL {i+1} ~~ ")   
    print(irt)

 ~~ PORTAL 1 ~~
             conteo  pct_tot  pct_rel
Interesados     141    1.000    1.000
Registrados      32    0.227    0.227
Traspasados       3    0.021    0.094
 ~~ PORTAL 2 ~~
             conteo  pct_tot  pct_rel
Interesados      84    1.000    1.000
Registrados      82    0.976    0.976
Traspasados      82    0.976    1.000
 ~~ PORTAL 3 ~~
             conteo  pct_tot  pct_rel
Interesados      78    1.000    1.000
Registrados      77    0.987    0.987
Traspasados      77    0.987    1.000
 ~~ PORTAL 4 ~~
             conteo  pct_tot  pct_rel
Interesados      42    1.000    1.000
Registrados      40    0.952    0.952
Traspasados      40    0.952    1.000

In [7]:
from src.kpis import full_funnel_pipeline

# EMBUDO 
## Exp -> vis -> cons -> inter -> reg -> tras

## TOTAL MKT

In [8]:
full_funnel_pipeline(estad_portales= ESTAD_PORTALES,
                     inter_portales= INTERESADOS,
                     crm_df= crm_df)

                 conteo  pct_tot  pct_rel
Exposición       226173    1.000    1.000
Visualizaciones    8656    0.038    0.038
Interesados         203    0.001    0.023
Registrados         199    0.001    0.980
Traspasados         199    0.001    1.000

## POR PORTAL

In [9]:
for i in range(4):
    fembudo = full_funnel_pipeline(estad_portales= stats[i],
                     inter_portales= inter[i],
                     crm_df= crm_df, 
                     start = i,
                     stop = i+1, 
                     include_consultas= False,
                     include_interesados= True)

    print(f" ~~ PORTAL {i+1} ~~ ")
    print(fembudo)

 ~~ PORTAL 1 ~~
                 conteo  pct_tot  pct_rel
Exposición       146410    1.000    1.000
Visualizaciones    6546    0.045    0.045
Interesados         141    0.001    0.022
Registrados          32    0.000    0.227
Traspasados           3    0.000    0.094
 ~~ PORTAL 2 ~~
                 conteo  pct_tot  pct_rel
Exposición       128418    1.000    1.000
Visualizaciones    4576    0.036    0.036
Interesados          83    0.001    0.018
Registrados          82    0.001    0.988
Traspasados          82    0.001    1.000
 ~~ PORTAL 3 ~~
                 conteo  pct_tot  pct_rel
Exposición        36337    1.000    1.000
Visualizaciones    2270    0.062    0.062
Interesados          78    0.002    0.034
Registrados          77    0.002    0.987
Traspasados          77    0.002    1.000
 ~~ PORTAL 4 ~~
                 conteo  pct_tot  pct_rel
Exposición        61418    1.000    1.000
Visualizaciones    1810    0.029    0.029
Interesados          42    0.001    0.023
Registrados          40    0.001    0.952
Traspasados          40    0.001    1.000

## TRASPASOS POR PASANTE

In [10]:
traspasos_por_pasante(inter_df = INTERESADOS,
                      crm_df = crm_df,
                      start = 2,
                      stop = 4
)

Código asesor
Alfredo Jimenez    115
Lesly Madariaga     84
Name: E-mail, dtype: int64