In [1]:
# ~~ TERCEROS ~~ #
import pandas as pd 
# ~~ ESTE PROYECTO ~~ #
import set_paths
from config.paths import *
from src.mkt import traspasos_por_pasante
from src.utils import get_files
from src.kpis import evci_pipeline, irt_pipeline, full_funnel_pipeline

# EMBUDOS
### Exposición -> Visualizaciones -> Consultas recibidas

## TOTAL MKT

In [10]:
embudo_mkt = evci_pipeline(estad_portales= ESTAD_PORTALES,
              inter_portales = INTERESADOS,
              pct_decimals = 3,
              start = 2,
              stop = 5)
embudo_mkt

                 conteo  pct_tot  pct_rel
Exposición       244764    1.000    1.000
Visualizaciones    9768    0.040    0.040
Interesados         236    0.001    0.024

## POR PORTAL

In [3]:
stats = [pd.read_excel(ESTAD_PORTALES / file) for file in get_files(ESTAD_PORTALES)]
inter = [pd.read_excel(INTERESADOS / file) for file in get_files(INTERESADOS)]
for i in range(4):
    embudo_portal = evci_pipeline(estad_portales= stats[i],
              inter_portales = inter[i],
              pct_decimals = 3,
              start = i,
              stop = i+1)
    print(f" ~~ PORTAL {i+1} ~~ ")
    print(embudo_portal)

 ~~ PORTAL 1 ~~
                 conteo  pct_tot  pct_rel
Exposición       152501    1.000    1.000
Visualizaciones    8068    0.053    0.053
Interesados         177    0.001    0.022
 ~~ PORTAL 2 ~~
                 conteo  pct_tot  pct_rel
Exposición       126530    1.000    1.000
Visualizaciones    5109    0.040    0.040
Interesados         109    0.001    0.021
 ~~ PORTAL 3 ~~
                 conteo  pct_tot  pct_rel
Exposición        35146    1.000    1.000
Visualizaciones    2047    0.058    0.058
Interesados          72    0.002    0.035
 ~~ PORTAL 4 ~~
                 conteo  pct_tot  pct_rel
Exposición        83088    1.000    1.000
Visualizaciones    2612    0.031    0.031
Interesados          55    0.001    0.021

## INTERESADOS vs REGISTROS vs TRASPASOS

### MARKETING

In [5]:
crm_df = pd.read_csv(CRM / get_files(CRM)[0])
irt_pipeline(crm_df= crm_df, 
             interesados=  INTERESADOS)

             conteo  pct_tot  pct_rel
Interesados     236    1.000    1.000
Registrados     226    0.958    0.958
Traspasados     226    0.958    1.000

## Por portal

In [6]:
for i in range(4):
    irt = irt_pipeline(crm_df= crm_df, 
             interesados= inter[i])
    print(f" ~~ PORTAL {i+1} ~~ ")   
    print(irt)

 ~~ PORTAL 1 ~~
             conteo  pct_tot  pct_rel
Interesados     177    1.000    1.000
Registrados      15    0.085    0.085
Traspasados       2    0.011    0.133
 ~~ PORTAL 2 ~~
             conteo  pct_tot  pct_rel
Interesados     109    1.000    1.000
Registrados     103    0.945    0.945
Traspasados     103    0.945    1.000
 ~~ PORTAL 3 ~~
             conteo  pct_tot  pct_rel
Interesados      72    1.000    1.000
Registrados      70    0.972    0.972
Traspasados      70    0.972    1.000
 ~~ PORTAL 4 ~~
             conteo  pct_tot  pct_rel
Interesados      55    1.000    1.000
Registrados      53    0.964    0.964
Traspasados      53    0.964    1.000

# EMBUDO 
## Exp -> vis -> cons -> inter -> reg -> tras

## TOTAL MKT

In [7]:
full_funnel_pipeline(estad_portales= ESTAD_PORTALES,
                     inter_portales= INTERESADOS,
                     crm_df= crm_df)

                 conteo  pct_tot  pct_rel
Exposición       244764    1.000    1.000
Visualizaciones    9768    0.040    0.040
Interesados         236    0.001    0.024
Registrados         226    0.001    0.958
Traspasados         226    0.001    1.000

## POR PORTAL

In [8]:
for i in range(4):
    fembudo = full_funnel_pipeline(estad_portales= stats[i],
                     inter_portales= inter[i],
                     crm_df= crm_df, 
                     start = i,
                     stop = i+1, 
                     include_consultas= False,
                     include_interesados= True)

    print(f" ~~ PORTAL {i+1} ~~ ")
    print(fembudo)

 ~~ PORTAL 1 ~~
                 conteo  pct_tot  pct_rel
Exposición       152501    1.000    1.000
Visualizaciones    8068    0.053    0.053
Interesados         177    0.001    0.022
Registrados          15    0.000    0.085
Traspasados           2    0.000    0.133
 ~~ PORTAL 2 ~~
                 conteo  pct_tot  pct_rel
Exposición       126530    1.000    1.000
Visualizaciones    5109    0.040    0.040
Interesados         109    0.001    0.021
Registrados         103    0.001    0.945
Traspasados         103    0.001    1.000
 ~~ PORTAL 3 ~~
                 conteo  pct_tot  pct_rel
Exposición        35146    1.000    1.000
Visualizaciones    2047    0.058    0.058
Interesados          72    0.002    0.035
Registrados          70    0.002    0.972
Traspasados          70    0.002    1.000
 ~~ PORTAL 4 ~~
                 conteo  pct_tot  pct_rel
Exposición        83088    1.000    1.000
Visualizaciones    2612    0.031    0.031
Interesados          55    0.001    0.021
Registrados          53    0.001    0.964
Traspasados          53    0.001    1.000

## TRASPASOS POR PASANTE

In [9]:
traspasos_por_pasante(inter_df = INTERESADOS,
                      crm_df = crm_df,
                      start = 2,
                      stop = 4
)

Código asesor
Alfredo Jimenez    118
Lesly Madariaga    108
Name: E-mail, dtype: int64