In [1]:
# ~~ TERCEROS ~~ #
import pandas as pd 
# ~~ ESTE PROYECTO ~~ #
import set_paths
from config.paths import *
from src.mkt import traspasos_por_pasante
from src.utils import get_files
from src.kpis import evci_pipeline, irt_pipeline, full_funnel_pipeline

# EMBUDOS
### Exposición -> Visualizaciones -> Consultas recibidas

## TOTAL MKT

In [2]:
embudo_mkt = evci_pipeline(estad_portales= ESTAD_PORTALES,
              inter_portales = INTERESADOS,
              pct_decimals = 3,
              start = 2,
              stop = 4)
embudo_mkt

                 conteo  pct_tot  pct_rel
Exposición       226173    1.000    1.000
Visualizaciones    8656    0.038    0.038
Interesados         203    0.001    0.023

## POR PORTAL

In [3]:
stats = [pd.read_excel(ESTAD_PORTALES / file) for file in get_files(ESTAD_PORTALES)]
inter = [pd.read_excel(INTERESADOS / file) for file in get_files(INTERESADOS)]
for i in range(4):
    embudo_portal = evci_pipeline(estad_portales= stats[i],
              inter_portales = inter[i],
              pct_decimals = 3,
              start = i,
              stop = i+1)
    print(f" ~~ PORTAL {i+1} ~~ ")
    print(embudo_portal)

 ~~ PORTAL 1 ~~
                 conteo  pct_tot  pct_rel
Exposición       146410    1.000    1.000
Visualizaciones    6546    0.045    0.045
Interesados         141    0.001    0.022
 ~~ PORTAL 2 ~~
                 conteo  pct_tot  pct_rel
Exposición       128418    1.000    1.000
Visualizaciones    4576    0.036    0.036
Interesados          83    0.001    0.018
 ~~ PORTAL 3 ~~
                 conteo  pct_tot  pct_rel
Exposición        36337    1.000    1.000
Visualizaciones    2270    0.062    0.062
Interesados          78    0.002    0.034
 ~~ PORTAL 4 ~~
                 conteo  pct_tot  pct_rel
Exposición        61418    1.000    1.000
Visualizaciones    1810    0.029    0.029
Interesados          42    0.001    0.023

## INTERESADOS vs REGISTROS vs TRASPASOS

### MARKETING

In [4]:
crm_df = pd.read_csv(CRM / get_files(CRM)[2])
irt_pipeline(crm_df= crm_df, 
             interesados=  INTERESADOS)

             conteo  pct_tot  pct_rel
Interesados     204    1.000    1.000
Registrados       1    0.005    0.005
Traspasados       1    0.005    1.000

## Por portal

In [5]:
for i in range(4):
    irt = irt_pipeline(crm_df= crm_df, 
             interesados= inter[i])
    print(f" ~~ PORTAL {i+1} ~~ ")   
    print(irt)

 ~~ PORTAL 1 ~~
             conteo  pct_tot  pct_rel
Interesados     141      1.0      1.0
Registrados       0      0.0      0.0
Traspasados       0      0.0      NaN
 ~~ PORTAL 2 ~~
             conteo  pct_tot  pct_rel
Interesados      84      1.0      1.0
Registrados       0      0.0      0.0
Traspasados       0      0.0      NaN
 ~~ PORTAL 3 ~~
             conteo  pct_tot  pct_rel
Interesados      78    1.000    1.000
Registrados       1    0.013    0.013
Traspasados       1    0.013    1.000
 ~~ PORTAL 4 ~~
             conteo  pct_tot  pct_rel
Interesados      42      1.0      1.0
Registrados       0      0.0      0.0
Traspasados       0      0.0      NaN

c:\Users\Dense\ALTALTIUM\TAREAS\KPIS\src\mkt.py:141: RuntimeWarning: invalid value encountered in scalar divide
  embudo["pct_rel"] = [1] + [np.round(embudo.iloc[i].iloc[0]/embudo.iloc[i-1].iloc[0], pct_decimals)
c:\Users\Dense\ALTALTIUM\TAREAS\KPIS\src\mkt.py:141: RuntimeWarning: invalid value encountered in scalar divide
  embudo["pct_rel"] = [1] + [np.round(embudo.iloc[i].iloc[0]/embudo.iloc[i-1].iloc[0], pct_decimals)
c:\Users\Dense\ALTALTIUM\TAREAS\KPIS\src\mkt.py:141: RuntimeWarning: invalid value encountered in scalar divide
  embudo["pct_rel"] = [1] + [np.round(embudo.iloc[i].iloc[0]/embudo.iloc[i-1].iloc[0], pct_decimals)

# EMBUDO 
## Exp -> vis -> cons -> inter -> reg -> tras

## TOTAL MKT

In [6]:
full_funnel_pipeline(estad_portales= ESTAD_PORTALES,
                     inter_portales= INTERESADOS,
                     crm_df= crm_df)

                 conteo  pct_tot  pct_rel
Exposición       226173    1.000    1.000
Visualizaciones    8656    0.038    0.038
Interesados         203    0.001    0.023
Registrados           1    0.000    0.005
Traspasados           1    0.000    1.000

## POR PORTAL

In [7]:
for i in range(4):
    fembudo = full_funnel_pipeline(estad_portales= stats[i],
                     inter_portales= inter[i],
                     crm_df= crm_df, 
                     start = i,
                     stop = i+1, 
                     include_consultas= False,
                     include_interesados= True)

    print(f" ~~ PORTAL {i+1} ~~ ")
    print(fembudo)

 ~~ PORTAL 1 ~~
                 conteo  pct_tot  pct_rel
Exposición       146410    1.000    1.000
Visualizaciones    6546    0.045    0.045
Interesados         141    0.001    0.022
Registrados           0    0.000    0.000
Traspasados           0    0.000      NaN
 ~~ PORTAL 2 ~~
                 conteo  pct_tot  pct_rel
Exposición       128418    1.000    1.000
Visualizaciones    4576    0.036    0.036
Interesados          83    0.001    0.018
Registrados           0    0.000    0.000
Traspasados           0    0.000      NaN
 ~~ PORTAL 3 ~~
                 conteo  pct_tot  pct_rel
Exposición        36337    1.000    1.000
Visualizaciones    2270    0.062    0.062
Interesados          78    0.002    0.034
Registrados           1    0.000    0.013
Traspasados           1    0.000    1.000
 ~~ PORTAL 4 ~~
                 conteo  pct_tot  pct_rel
Exposición        61418    1.000    1.000
Visualizaciones    1810    0.029    0.029
Interesados          42    0.001    0.023
Registrados           0    0.000    0.000
Traspasados           0    0.000      NaN

c:\Users\Dense\ALTALTIUM\TAREAS\KPIS\src\mkt.py:141: RuntimeWarning: invalid value encountered in scalar divide
  embudo["pct_rel"] = [1] + [np.round(embudo.iloc[i].iloc[0]/embudo.iloc[i-1].iloc[0], pct_decimals)
c:\Users\Dense\ALTALTIUM\TAREAS\KPIS\src\mkt.py:141: RuntimeWarning: invalid value encountered in scalar divide
  embudo["pct_rel"] = [1] + [np.round(embudo.iloc[i].iloc[0]/embudo.iloc[i-1].iloc[0], pct_decimals)
c:\Users\Dense\ALTALTIUM\TAREAS\KPIS\src\mkt.py:141: RuntimeWarning: invalid value encountered in scalar divide
  embudo["pct_rel"] = [1] + [np.round(embudo.iloc[i].iloc[0]/embudo.iloc[i-1].iloc[0], pct_decimals)
c:\Users\Dense\ALTALTIUM\TAREAS\KPIS\src\mkt.py:141: RuntimeWarning: invalid value encountered in scalar divide
  embudo["pct_rel"] = [1] + [np.round(embudo.iloc[i].iloc[0]/embudo.iloc[i-1].iloc[0], pct_decimals)
c:\Users\Dense\ALTALTIUM\TAREAS\KPIS\src\mkt.py:141: RuntimeWarning: invalid value encountered in scalar divide
  embudo["pct_rel"] = [1] + [np.round(embudo.iloc[i].iloc[0]/embudo.iloc[i-1].iloc[0], pct_decimals)
c:\Users\Dense\ALTALTIUM\TAREAS\KPIS\src\mkt.py:141: RuntimeWarning: invalid value encountered in scalar divide
  embudo["pct_rel"] = [1] + [np.round(embudo.iloc[i].iloc[0]/embudo.iloc[i-1].iloc[0], pct_decimals)

## TRASPASOS POR PASANTE

In [8]:
traspasos_por_pasante(inter_df = INTERESADOS,
                      crm_df = crm_df,
                      start = 2,
                      stop = 4
)

Código asesor
Lesly Madariaga    1
Name: E-mail, dtype: int64