In [1]:
# ~~ TERCEROS ~~ #
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# ~~ ESTE PROYECTO ~~ #
import set_paths
from config.paths import *
from src.preprocessing import concat_tables
from src.mkt import (embudo, 
                     add_unique_interested, 
                     join_inter_crm, 
                     reg_vs_inter, 
                     tras_vs_reg)
from src.utils import get_files
from src.kpis import evci_pipeline, irt_pipeline

# EMBUDOS
### Exposición -> Visualizaciones -> Consultas recibidas

## TOTAL MKT

In [3]:
embudo_mkt = evci_pipeline(estad_portales= ESTAD_PORTALES,
              inter_portales = INTERESADOS,
              pct_decimals = 3,
              start = 2,
              stop = 4)
embudo_mkt

                 conteo  pct_tot  pct_rel
Exposición       220521    1.000    1.000
Visualizaciones    7732    0.035    0.035
Interesados         228    0.001    0.029

## POR PORTAL

In [4]:
stats = [pd.read_excel(ESTAD_PORTALES / file) for file in get_files(ESTAD_PORTALES)]
inter = [pd.read_excel(INTERESADOS / file) for file in get_files(INTERESADOS)]
for i in range(4):
    embudo_portal = evci_pipeline(estad_portales= stats[i],
              inter_portales = inter[i],
              pct_decimals = 3,
              start = i,
              stop = i+1)
    print(f" ~~ PORTAL {i+1} ~~ ")
    print(embudo_portal)

 ~~ PORTAL 1 ~~
                 conteo  pct_tot  pct_rel
Exposición       126028    1.000    1.000
Visualizaciones    5450    0.043    0.043
Interesados         127    0.001    0.023
 ~~ PORTAL 2 ~~
                 conteo  pct_tot  pct_rel
Exposición       131415    1.000    1.000
Visualizaciones    4449    0.034    0.034
Interesados         112    0.001    0.025
 ~~ PORTAL 3 ~~
                 conteo  pct_tot  pct_rel
Exposición        35000    1.000    1.000
Visualizaciones    1784    0.051    0.051
Interesados          86    0.002    0.048
 ~~ PORTAL 4 ~~
                 conteo  pct_tot  pct_rel
Exposición        54106    1.000    1.000
Visualizaciones    1499    0.028    0.028
Interesados          30    0.001    0.020

## INTERESADOS vs REGISTROS vs TRASPASOS

### MARKETING

In [5]:
crm_df = pd.read_csv(CRM / get_files(CRM)[0])
irt_pipeline(crm_df= crm_df, 
             interesados=  INTERESADOS)

             conteo  pct_tot  pct_rel
Interesados     229    1.000    1.000
Registrados     223    0.974    0.974
Traspasados     223    0.974    1.000

## Por portal

In [6]:
for i in range(4):
    irt = irt_pipeline(crm_df= crm_df, 
             interesados= inter[i])
    print(f" ~~ PORTAL {i+1} ~~ ")   
    print(irt)

 ~~ PORTAL 1 ~~
             conteo  pct_tot  pct_rel
Interesados     127    1.000    1.000
Registrados      14    0.110    0.110
Traspasados       1    0.008    0.071
 ~~ PORTAL 2 ~~
             conteo  pct_tot  pct_rel
Interesados     113    1.000    1.000
Registrados     111    0.982    0.982
Traspasados     111    0.982    1.000
 ~~ PORTAL 3 ~~
             conteo  pct_tot  pct_rel
Interesados      86    1.000    1.000
Registrados      82    0.953    0.953
Traspasados      82    0.953    1.000
 ~~ PORTAL 4 ~~
             conteo  pct_tot  pct_rel
Interesados      30      1.0      1.0
Registrados      30      1.0      1.0
Traspasados      30      1.0      1.0

In [7]:
from src.kpis import full_funnel_pipeline

# EMBUDO 
## Exp -> vis -> cons -> inter -> reg -> tras

## TOTAL MKT

In [8]:
full_funnel_pipeline(estad_portales= ESTAD_PORTALES,
                     inter_portales= INTERESADOS,
                     crm_df= crm_df)

                 conteo  pct_tot  pct_rel
Exposición       220521    1.000    1.000
Visualizaciones    7732    0.035    0.035
Interesados         228    0.001    0.029
Registrados         223    0.001    0.978
Traspasados         223    0.001    1.000

## POR PORTAL

In [13]:
for i in range(4):
    fembudo = full_funnel_pipeline(estad_portales= stats[i],
                     inter_portales= inter[i],
                     crm_df= crm_df, 
                     start = i,
                     stop = i+1, 
                     include_consultas= False,
                     include_interesados= True)

    print(f" ~~ PORTAL {i+1} ~~ ")
    print(fembudo)

 ~~ PORTAL 1 ~~
                 conteo  pct_tot  pct_rel
Exposición       126028    1.000    1.000
Visualizaciones    5450    0.043    0.043
Interesados         127    0.001    0.023
Registrados          14    0.000    0.110
Traspasados           1    0.000    0.071
 ~~ PORTAL 2 ~~
                 conteo  pct_tot  pct_rel
Exposición       131415    1.000    1.000
Visualizaciones    4449    0.034    0.034
Interesados         112    0.001    0.025
Registrados         111    0.001    0.991
Traspasados         111    0.001    1.000
 ~~ PORTAL 3 ~~
                 conteo  pct_tot  pct_rel
Exposición        35000    1.000    1.000
Visualizaciones    1784    0.051    0.051
Interesados          86    0.002    0.048
Registrados          82    0.002    0.953
Traspasados          82    0.002    1.000
 ~~ PORTAL 4 ~~
                 conteo  pct_tot  pct_rel
Exposición        54106    1.000    1.000
Visualizaciones    1499    0.028    0.028
Interesados          30    0.001    0.020
Registrados          30    0.001    1.000
Traspasados          30    0.001    1.000